# Generated by Django 5.2.4 on 2025-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Other', 'Other')], max_length=50),
        ),
    ]
